# Generated by Django 3.2 on 2024-11-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('type_proprietaire', models.CharField(choices=[('PROFESSIONNEL', 'PROFESSIONNEL'), ('PARTICULIER', 'PARTICULIER')], max_length=100)),
                ('nom_raison_sociale', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('nom_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_gardien', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_gardien', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Propriétaires',
            },
        ),
    ]
