# Generated by Django 3.2 on 2024-11-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='nom_proprietaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='tel_proprietaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
