# Generated by Django 3.2 on 2025-04-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaires', '0002_auto_20241113_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
