# Generated by Django 3.2 on 2024-11-05 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Intermidiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Intermidiaires',
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Résidences',
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Secteurs',
            },
        ),
        migrations.CreateModel(
            name='Typebien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Types de Bien',
            },
        ),
        migrations.CreateModel(
            name='Soustypebien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietes.typebien')),
            ],
            options={
                'verbose_name_plural': 'Sous Type de Bien',
            },
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_operation', models.CharField(choices=[('LOCATION LONGUE DUREE', 'LOCATION LONGUE DUREE'), ('LOCATION COURTE DUREE', 'LOCATION COURTE DUREE'), ('VENTE', 'VENTE')], max_length=50)),
                ('num_appartment', models.CharField(blank=True, max_length=20, null=True)),
                ('global_bedrooms', models.CharField(blank=True, max_length=100, null=True)),
                ('suite_number', models.CharField(blank=True, max_length=100, null=True)),
                ('master_number', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie_habitable', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie_terrain', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie_construite', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie_sol', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie_terrasse', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie_jardin', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie_coure', models.CharField(blank=True, max_length=100, null=True)),
                ('residentiel', models.BooleanField(default=False)),
                ('individuel', models.BooleanField(default=False)),
                ('immeuble', models.BooleanField(default=False)),
                ('habitation', models.BooleanField(default=False)),
                ('commercial', models.BooleanField(default=False)),
                ('mixte', models.BooleanField(default=False)),
                ('recent', models.BooleanField(default=False)),
                ('ancien', models.BooleanField(default=False)),
                ('neuf', models.BooleanField(default=False)),
                ('a_renover', models.BooleanField(default=False)),
                ('semi_fini', models.BooleanField(default=False)),
                ('economique', models.BooleanField(default=False)),
                ('haut_standing', models.BooleanField(default=False)),
                ('my_standing', models.BooleanField(default=False)),
                ('vide', models.BooleanField(default=False)),
                ('semi_meuble', models.BooleanField(default=False)),
                ('meuble', models.BooleanField(default=False)),
                ('equipee', models.BooleanField(default=False)),
                ('semi_equipee', models.BooleanField(default=False)),
                ('collective', models.BooleanField(default=False)),
                ('titree', models.BooleanField(default=False)),
                ('adresse', models.TextField()),
                ('nbre_salon_marocain', models.CharField(blank=True, max_length=100, null=True)),
                ('nbre_salon_european', models.CharField(blank=True, max_length=100, null=True)),
                ('nbre_salon_cheminie', models.CharField(blank=True, max_length=100, null=True)),
                ('nbre_salon_sejour', models.CharField(blank=True, max_length=100, null=True)),
                ('nbre_cuisine_independante', models.CharField(blank=True, max_length=100, null=True)),
                ('nbre_cuisine_kitchinette', models.CharField(blank=True, max_length=100, null=True)),
                ('nbre_cuisine_americaine', models.CharField(blank=True, max_length=100, null=True)),
                ('cuisine_equipee', models.BooleanField(default=False)),
                ('cuisine_amenagee', models.BooleanField(default=False)),
                ('cuisine_lesdeux', models.BooleanField(default=False)),
                ('cuisine_buanderie', models.BooleanField(default=False)),
                ('bathrooms_italienne', models.CharField(blank=True, max_length=100, null=True)),
                ('bathrooms_baignoire', models.CharField(blank=True, max_length=100, null=True)),
                ('bathrooms_sde', models.CharField(blank=True, max_length=100, null=True)),
                ('bathrooms_hammam_beldi', models.CharField(blank=True, max_length=100, null=True)),
                ('nbre_terrasse', models.CharField(blank=True, max_length=100, null=True)),
                ('nbre_coure', models.CharField(blank=True, max_length=100, null=True)),
                ('nbre_balcon', models.CharField(blank=True, max_length=100, null=True)),
                ('nbre_c_anglaise', models.CharField(blank=True, max_length=100, null=True)),
                ('nbre_terrasse_toit', models.CharField(blank=True, max_length=100, null=True)),
                ('nbre_buanderie', models.CharField(blank=True, max_length=100, null=True)),
                ('piscine_privee', models.BooleanField(default=False)),
                ('piscine_chauffee_privee', models.BooleanField(default=False)),
                ('jacozzi_privee', models.BooleanField(default=False)),
                ('jardin_privee', models.BooleanField(default=False)),
                ('hammam_beldi_privee', models.BooleanField(default=False)),
                ('piscine_collective', models.BooleanField(default=False)),
                ('piscine_chauffee_collective', models.BooleanField(default=False)),
                ('jacozzi_collective', models.BooleanField(default=False)),
                ('jardin_collective', models.BooleanField(default=False)),
                ('hammam_beldi_collective', models.BooleanField(default=False)),
                ('ascenseur', models.BooleanField(default=False)),
                ('escalier_secour', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('syndic', models.BooleanField(default=False)),
                ('puit', models.BooleanField(default=False)),
                ('goute_a_goute', models.BooleanField(default=False)),
                ('local_technique', models.BooleanField(default=False)),
                ('chauffeau_electrique', models.BooleanField(default=False)),
                ('chauffeau_gaz', models.BooleanField(default=False)),
                ('climatisation_centrale', models.BooleanField(default=False)),
                ('climatisation_revirsible', models.BooleanField(default=False)),
                ('climatisation_mural', models.BooleanField(default=False)),
                ('origine_prospection', models.BooleanField(default=False)),
                ('origine_interne', models.BooleanField(default=False)),
                ('origine_intermidiaire', models.BooleanField(default=False)),
                ('genre_marocain', models.BooleanField(default=False)),
                ('genre_contemporain', models.BooleanField(default=False)),
                ('genre_moderne', models.BooleanField(default=False)),
                ('genre_traditionnel', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proprietes.agent')),
                ('intermidiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proprietes.intermidiaire')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietaires.proprietaire')),
                ('residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proprietes.residence')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietes.secteur')),
                ('sous_type_bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proprietes.soustypebien')),
                ('type_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietes.typebien')),
            ],
            options={
                'verbose_name_plural': 'Proprietés',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='images')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietes.propriete')),
            ],
        ),
    ]
