# Generated by Django 3.2 on 2024-11-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='propriete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proprietes.propriete'),
        ),
    ]
