# Generated by Django 3.2 on 2024-11-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('proprietes', '0003_auto_20241110_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soustypebien',
            name='type_bien',
        ),
        migrations.AlterField(
            model_name='propriete',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.agent'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='bathrooms_baignoire',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='bathrooms_hammam_beldi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='bathrooms_italienne',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='bathrooms_sde',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='intermidiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.intermidiaire'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.residence'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.secteur'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='sous_type_bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.soustypebien'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='type_bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.typebien'),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Intermidiaire',
        ),
        migrations.DeleteModel(
            name='Residence',
        ),
        migrations.DeleteModel(
            name='Secteur',
        ),
        migrations.DeleteModel(
            name='Soustypebien',
        ),
        migrations.DeleteModel(
            name='Typebien',
        ),
    ]
