# Generated by Django 3.2 on 2024-11-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0004_auto_20241111_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='avance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propriete',
            name='caution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propriete',
            name='loyer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='type_operation',
            field=models.CharField(choices=[('LOCATION LONGUE DUREE', 'LOCATION LONGUE DUREE'), ('LOCATION COURTE DUREE', 'LOCATION COURTE DUREE'), ('FOND DE COMMERCE', 'FOND DE COMMERCE'), ("DROIT D'ENTREE", "DROIT D'ENTREE"), ('VENTE', 'VENTE')], max_length=50),
        ),
    ]
