# Generated by Django 3.2 on 2024-11-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0005_auto_20241113_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='parking_collectif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propriete',
            name='parking_prive',
            field=models.BooleanField(default=False),
        ),
    ]
