# Generated by Django 3.2 on 2024-11-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_secteur_quartier_secteur'),
        ('proprietes', '0006_auto_20241113_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='quartier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.quartier'),
            preserve_default=False,
        ),
    ]
