# Generated by Django 3.2 on 2025-04-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0007_propriete_quartier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriete',
            name='adresse',
        ),
    ]
