# Generated by Django 3.2 on 2025-04-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0009_auto_20250408_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='exclusive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propriete',
            name='libre',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propriete',
            name='libre_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propriete',
            name='occuped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propriete',
            name='occuped_date',
            field=models.DateField(auto_now=True),
        ),
    ]
