# Generated by Django 3.2 on 2025-04-09 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0010_auto_20250409_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='libre_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='occuped_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
