# Generated by Django 3.2 on 2025-04-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0011_auto_20250409_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='libre_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='occuped_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
