# Generated by Django 3.2 on 2025-04-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietes', '0012_auto_20250409_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
