# Generated by Django 3.2 on 2024-11-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.secteur')),
            ],
            options={
                'verbose_name_plural': 'Quartiers',
            },
        ),
    ]
