# Generated by Django 3.2 on 2025-04-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_secteur_quartier_secteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typebien',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
