# Generated by Django 3.2 on 2025-04-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20250406_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
