# Generated by Django 3.2 on 2025-04-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_residence_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_agent/'),
        ),
    ]
