# Generated by Django 3.2 on 2025-04-07 20:09

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_agent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermidiaire',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=settings.models.renommer_image_intermidiaire),
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=settings.models.renommer_image_agent),
        ),
    ]
