# Generated by Django 3.2 on 2024-11-05 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietes', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('VENTE', 'VENTE'), ('LOCATION', 'LOCATION')], max_length=200)),
                ('date_operation', models.DateField(max_length=255)),
                ('prix_operation', models.IntegerField()),
                ('duree_operation', models.CharField(choices=[('FERME', 'FERME'), ('SIX MOIS FERME', 'SIX MOIS FERME'), ('SIX MOIS RENOUVELABLE', 'SIX MOIS RENOUVELABLE'), ('UNE ANNEE FERMEE', 'UNE ANNEE FERMEE'), ('UNE ANNEE RENOUVELABLE', 'UNE ANNEE RENOUVELABLE')], max_length=200)),
                ('monant_commission', models.IntegerField()),
                ('numero_contrat', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietes.propriete')),
            ],
            options={
                'verbose_name_plural': 'Operation',
            },
        ),
    ]
