# Generated by Django 3.2 on 2024-11-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='type_operation',
        ),
    ]
