# Generated by Django 3.2 on 2024-11-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_operation_type_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('LOCATION LONGUE DUREE', 'LOCATION LONGUE DUREE'), ('LOCATION COURTE DUREE', 'LOCATION COURTE DUREE'), ('FOND DE COMMERCE', 'FOND DE COMMERCE'), ("DROIT D'ENTREE", "DROIT D'ENTREE"), ('VENTE', 'VENTE')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
