# Generated by Django 3.2 on 2025-04-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operation_type_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
